# Install pandoc-aozora-ruby filter
# https://github.com/minoki/pandoc-aozora-ruby
# FROM haskell as filter-builder
# RUN apk add --no-cache --virtual .filter-deps \
#     git clone https://github.com/minoki/pandoc-aozora-ruby.git && \
#     cd pandoc-aozora-ruby && \
#     stack install --local-bin-path 

